name: Lint CloudFormation Templates

on: push

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cfn
        uses: actions/checkout@v2

      - name: Check out code on branch
        uses: actions/checkout@v2

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Testing with CFN Lint Command
        run: |
          cd $GITHUB_WORKSPACE
          cfn-lint --version 
          cfn-lint -t ./**/*.yaml 